### ISSUE TITLE
2022年10月23日还可以正常使用吗？

### ISSUE THREAD

**Issue by LittleHeroZZZX** [xsk666/xxt_work_notice#1]
运行xxt_Homework_Notice.py提示`登陆失败 'mes'`，已确认账号密码正确无误。

**Comment by xsk666** [comment]
一直都可以的啊，用手机号登陆

**Comment by LittleHeroZZZX** [comment]
看了一下错误原因，登录成功的话服务器不再返回`msg`字段了，您可以修改一下登录状态的判断逻辑，根据`status`这个字段来确认是否登录成功。

**Comment by xsk666** [comment]
我这边的登录返回如下
`{'mes': '验证通过', 'type': 1, 'url': 'https://sso.chaoxing.com/apis/login/userLogin4Uname.do', 'status': True}`
十分感谢你的建议，已修改
